defaults:
    - _self_
    - model: glow_joint
    - dataset: glow_data
    - override hydra/hydra_logging: none
    - override hydra/job_logging: none

network_type: glow
use_DFCData: True
use_Shadow: True

# dirs
exp_dir: ./runs/exp_glow

# wandb
wandb_offline: True
wandb_debug_mode: True  # and only program error will be reported

# frequency
freq:
    step_epoch: 100
    save: 10000  # per iter
    plot: 100  # per iter
    test: 50000 # per iter

# optimization options
optimizer: Adam
weight_decay: 0.0001
learning_rate: 0.001
lr_policy: step
lr_gamma: 0.5 # lr decay rate
lr_step_size: 40
lr_clip: 0.00001 # min lr

# bn momentum adjustment
momentum_original: 0.1
momentum_decay: 0.5
momentum_step_size: 20  # = lr_step_size
momentum_min: 0.01

# training options
weight_init: xavier
total_epoch: 2000
resume_epoch: -1

# device
cuda_id: 0

# data loader
num_workers: 1
batch_size: 32

# hydra
hydra:
    output_subdir: null
